### ISSUE TITLE
Feature: shareable swatch color urls

### ISSUE THREAD

**Issue by Belco90** [ivan-dalmet/smart-swatch#4]
Hey Ivan! I love this project. I use it **a lot** in both professional and personal projects to generate proper HUEs for Chakra-UI.

However, I'd like to be able to share a generated swatch for a color with someone else through a shareable url so I can reference the HUE in tickets or show them to someone else.

I'm happy to implement this myself. Should be as easy as get/set the url hash with the color, init the input with it, and add an icon button at the right of the main input for copying the shareable url (if you like this approach). Before creating the PR, I'd like you to confirm if this is fine.

Thanks!.

**Comment by ivan-dalmet** [comment]
Oh! So happy that it helps ☺️
I will be happy to have this feature too but I don't have time to do it.
So yes if you have time, feel free to submit a PR with this feature 🤗
